In [ ]:
import tensorflow as tf

# Different tensors


In [ ]:
tensor_0_d = tf.constant(1)
print(tensor_0_d)

tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([1,2,3])
print(tensor_one_d)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
tensor_two_D = tf.constant([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(tensor_two_D.shape)
print(tensor_two_D.ndim)


(4, 3)
2


In [ ]:
tensor_three_D = tf.constant(
    [
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]],
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
        ])
print(tensor_three_D)


tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
# for the shape and dimension of the tensor
print("the number of dimension: ", tensor_three_D.ndim)
print("the shape of the tensor : ", tensor_three_D.shape)


the number of dimension:  3
the shape of the tensor :  (4, 2, 3)


# 1d combines > 2d combines > 3d combines > 4d

In [ ]:
tensor_four_d = tf.constant([
   [ [[1,2,3],
     [4,5,6],
     [1,2,3]],
    [[7,8,9],
     [10,11,12],
     [1,2,3]],
    [[1,2,3],
     [4,5,6],
     [1,2,3]],
    [[7,8,9],
     [10,11,12],
     [1,2,3]]]
        ,

   [ [[11,22,33],
     [4,5,6],
     [1,2,3]],
    [[73,83,93],
     [10,11,12],
     [1,2,3]],
    [[13,2,3],
     [43,5,6],
     [1,2,3]],
    [[73,8,9],
     [10,131,12],
     [1,2,3]]]
        ,

   [ [[13,32,33],
     [43,54,65],
     [1,2,3]],
    [[7,8,9],
     [130,11,12],
     [1,2,3]],
    [[13,25,36],
     [41,25,64],
     [1,2,3]],
    [[75,86,97],
     [1022,1125,1225],
     [1,2,2]
     ]]
        ])
print(tensor_four_d)

tf.Tensor(
[[[[   1    2    3]
   [   4    5    6]
   [   1    2    3]]

  [[   7    8    9]
   [  10   11   12]
   [   1    2    3]]

  [[   1    2    3]
   [   4    5    6]
   [   1    2    3]]

  [[   7    8    9]
   [  10   11   12]
   [   1    2    3]]]


 [[[  11   22   33]
   [   4    5    6]
   [   1    2    3]]

  [[  73   83   93]
   [  10   11   12]
   [   1    2    3]]

  [[  13    2    3]
   [  43    5    6]
   [   1    2    3]]

  [[  73    8    9]
   [  10  131   12]
   [   1    2    3]]]


 [[[  13   32   33]
   [  43   54   65]
   [   1    2    3]]

  [[   7    8    9]
   [ 130   11   12]
   [   1    2    3]]

  [[  13   25   36]
   [  41   25   64]
   [   1    2    3]]

  [[  75   86   97]
   [1022 1125 1225]
   [   1    2    2]]]], shape=(3, 4, 3, 3), dtype=int32)




> **dtype changing would affect the datatype**



In [ ]:
tensor_three_D_float32 = tf.constant(
    [
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]],
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
        ], dtype=tf.float32)
print(tensor_three_D_float)

tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(4, 2, 3), dtype=float32)


In [ ]:
tensor_one_d = tf.constant([1,2,3], dtype=tf.float64)
casted_one_d = tf.cast(tensor_one_d, dtype=tf.int16)
print(tensor_one_d)
print(casted_one_d)
# tensor bool
tensor_bool = tf.constant ([True, False, True])
print(tensor_bool)


tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)
tf.Tensor([1 2 3], shape=(3,), dtype=int16)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)
